#!/bin/bash

# depends git
# depends yarn

shef apt xclip

# Scaffolding
mkdir -p ~/.cache/configuration

shef brew yarn

shef npm grunt-cli

# Building workspace
# ------------------

WORKSPACE_PATH=$HOME/Projects
if [ ! -d "$WORKSPACE_PATH" ]; then
    mkdir -p "$WORKSPACE_PATH"
fi

# Retrieving sources

if [ -f "$HOME/.workspace-install" ]; then
  source "$HOME/.workspace-install"

  if [ ! -d "$WORKSPACE_PATH" ]; then
      shef git --repository "$WORKSPACE_GIT_URL" --destination "$WORKSPACE_PATH" --enable-submodules
  fi
fi

# Install graphviz
# Install graph-composer
