#!/bin/bash

# depends git
# depends yarn

shef apt xclip

# Scaffolding
mkdir -p ~/.cache/configuration

shef brew yarn

shef npm grunt-cli
shef apt default-jdk
shef code --code "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823"
shef apt --package sbt --repository "deb https://dl.bintray.com/sbt/debian /"

# Building workspace
# ------------------

WORKSPACE_PATH=$HOME/Projects
if [ ! -d "$WORKSPACE_PATH" ]; then
    mkdir -p "$WORKSPACE_PATH"
fi

# Retrieving sources

if [ -f "$HOME/.workspace-install" ]; then
  source "$HOME/.workspace-install"

  if [ ! -d "$WORKSPACE_PATH" ]; then
      shef git --repository "$WORKSPACE_GIT_URL" --destination "$WORKSPACE_PATH" --enable-submodules
  fi
fi

# Install graphviz
# Install graph-composer
