version: '3'
services:
    main-recipe:
      image: registry.gitlab.com/leonardmessier/shef/recipes/main-recipe:1.0.0
      build:
        context: ../
        dockerfile: .docker/Dockerfile
        args:
          - USERNAME=${USERNAME}
